Minor workflow fixes

diff --git a/.github/workflows/dev_build.yml b/.github/workflows/dev_build.yml
--- a/.github/workflows/dev_build.yml
+++ b/.github/workflows/dev_build.yml
@@ -54,7 +54,8 @@ jobs:
       SSH_USER: ${{ secrets.SSH_USER }}
       SSH_HOST: ${{ secrets.SSH_HOST }}
       SSH_PATH: ${{ secrets.SSH_PATH }}
-      SSH_KEY:  ${{ secrets.SSH_KEY }}
+      SSH_KEY: ${{ secrets.SSH_KEY }}
+      DEPLOY: ${{ vars.DEPLOY }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -66,14 +67,21 @@ jobs:
 
       - name: Deploy
         run: |
+          if [ -z "$DEPLOY" ] || [ "$DEPLOY" != 1  ] || [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ] || [ -z "$SSH_PATH" ] || [ -z "$SSH_KEY" ] || [ ! -f "docker-compose.yml" ] || [ ! -f "*.jar" ]; then
+            echo "Skipping deployment due to missing requirements"
+            exit 1
+          fi
+
           echo "Deploying service jar to server"
           artifact_name=$(ls *.jar)
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem
           ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "mkdir -p $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
           scp -o StrictHostKeyChecking=no -i key.pem *.jar $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/$artifact_name
+          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/docker-compose.yml
+          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "cd $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/} && docker-compose up -d"
 
       - name: Delete artifact
         uses: geekyeggo/delete-artifact@v1
         with:
-            name: service-jar
+          name: service-jar
