Improved CI/CD (#10)
* Minor workflow fixes
* Parameterized sensitive info in docker-compose.yml
* Parameterized sensitive info in app properties
* Improved deploy security and efficiency
* Added bash script to handle service deploy

diff --git a/.github/workflows/dev_build.yml b/.github/workflows/dev_build.yml
--- a/.github/workflows/dev_build.yml
+++ b/.github/workflows/dev_build.yml
@@ -48,6 +48,7 @@ jobs:
   deploy:
     name: Deploy Service
     permissions: write-all
+    environment: aws
     needs: build
     runs-on: ubuntu-latest
     env:
@@ -55,6 +56,9 @@ jobs:
       SSH_HOST: ${{ secrets.SSH_HOST }}
       SSH_PATH: ${{ secrets.SSH_PATH }}
       SSH_KEY:  ${{ secrets.SSH_KEY }}
+      ENV_FILE: ${{ secrets.ENV_FILE }}
+      DEPLOY:   ${{ vars.DEPLOY }}
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -66,14 +70,47 @@ jobs:
 
       - name: Deploy
         run: |
+          
+          if  [ "$DEPLOY" != 1  ]; then
+            echo "Skipping deployment due to missing requirements"
+            exit 1
+          fi
+          
+          if [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ] || [ -z "$SSH_PATH" ] || [ -z "$SSH_KEY" ]; then
+            echo "Missing required environment variables"
+            exit 1
+          fi
+
           echo "Deploying service jar to server"
+
           artifact_name=$(ls *.jar)
+          
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem
-          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "mkdir -p $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/dev"
-          scp -o StrictHostKeyChecking=no -i key.pem *.jar $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/dev/$artifact_name
+          
+          echo "$ENV_FILE" > .env
+          
+          if [ ! -f "docker-compose.yml" ]; then
+            echo "Missing docker-compose.yml"
+            exit 1
+          fi
+          
+          if [ ! -f "$artifact_name" ]; then
+            echo "Missing service jar"
+            exit 1
+          fi
+          
+          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "mkdir -p $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
+          
+          scp -o StrictHostKeyChecking=no -i key.pem *.jar $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/$artifact_name
+          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/docker-compose.yml
+          scp -o StrictHostKeyChecking=no -i key.pem .env $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/.env
+          scp -o StrictHostKeyChecking=no -i key.pem upservice.sh $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/upservice.sh
+          
+          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "cd $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/} ; sudo chmod +x upservice.sh ; ./upservice.sh"
 
       - name: Delete artifact
         uses: geekyeggo/delete-artifact@v1
         with:
-            name: service-jar
+          name: service-jar
+
